# 12 Lattice based cryptography

Find the shortest vector in $L(B)$. $n=2, d=2$

$$B = \begin{pmatrix}
1 & 3\\
2 & 2
\end{pmatrix}$$

The shortest vector is a linear combination of $a = \begin{pmatrix}
1\\
2
\end{pmatrix}$ and $b = \begin{pmatrix}
3\\
2
\end{pmatrix}$
with a small vector size in real space

in this case we can use $-a + b$ to get a vector of size 2

## Gram Schmidt

In [1]:
import numpy as np

In [10]:
def proj(u, v):
    coeff = np.dot(u, v)
    return coeff * u

In [16]:
def gram_schmidt(B):
    V = B.T
    u1 = V[0]
    u2 = V[1] - proj(u1, V[1])
    u3 = V[2] - proj(u1, V[2]) - proj(u2, V[2])
    
    B_ = np.array([u1, u2, u3])
    return B_.T

In [18]:
B = np.array([[1,2,3], [4,5,6], [-1, 0, 1], [2,2,2]])
print(B)
B_ = gram_schmidt(B)
print(B_)

[[ 1  2  3]
 [ 4  5  6]
 [-1  0  1]
 [ 2  2  2]]
[[     1    -24 -17787]
 [     4    -99 -73374]
 [    -1     26  19271]
 [     2    -50 -37058]]
